---
title: "About"
output: 
  html_document:
      toc: true
      toc_float: true
---

<br>

### **Motivation**
Since the start of COVID-19, a range of conspiracy theories have spun up in the United States about the scope and severity of the pandemic. The [President](https://apnews.com/article/virus-outbreak-donald-trump-ap-fact-check-anthony-fauci-flu-fe474f0c15f76adf324791a2cfc1e2bb) of the United States has repeatedly compared coronavirus to the flu, claiming that the lethality of the two diseases are comparable. These words are the reflection a larger population's attitude on 

<br>

### **Methods**

Data from five sources were considered for this project. The data sources, scraping methods and cleaning procedures for each dataset are described below. 

*  The Github repository for this project can be found [here](https://github.com/wx2233/p8105_final_project). 

*  The final website can be found [here](https://wx2233.github.io/p8105_final_project/)

* The shiny repository can be found [here](https://wx2233-shiny.shinyapps.io/final_shiny_dashboard/)

<br>

### **Data**
***NYPD Motor Vehicle Collisions-Crashes Data*** is from the [NYC Open Data](https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95). NYC Open Data is free public data published by New York City agencies and other partners. The Motor Vehicle Collisions data tables contain information from all police reported motor vehicle collisions in NYC. The police report [MV104-AN](https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/ny_overlay_mv-104an_rev05_2004.pdf) is required to be filled out for collisions where someone is injured or killed, or where there is at least $1000 worth of damage.

***DOHMH New York City Restaurant Inspection Results Data*** was obtained from the [NYC Open Data](https://data.cityofnewyork.us/Health/DOHMH-New-York-City-Restaurant-Inspection-Results/43nn-pn8j). The dataset was used to assess the association between the restaurant number and alcohol involved collision cases 

Data on ***U.S legal holidays*** was taken from the [Federal Holidays](https://www.redcort.com/us-federal-bank-holidays/).Federal holidays may affect the number of accidents since number of people going outside varies among holidays.  

***Traffic Signals Data*** is uploaded from [NYC Open Data](https://data.cityofnewyork.us/Transportation/DOT-Street-Lights-and-Traffic-Signals-311-Service-/jwvp-gyiq). This dataset contains all 311 Service Requests from 2010 to present which is automatically updated daily. Also, details related to services were included. 311 is a non-emergency phone number that people can call in many cities to find information about services, make complaints, or report problems like graffiti or road damage.

***Weather Data*** was taken from [National Centers For Environmental Information](https://www.ncdc.noaa.gov/cdo-web/search). It was used to figure out the influences given by different weather types, such as fog, sunny, mist etc,. Also, influences caused by levels of precipitation on accident events were also evaluated. 

<br>

### **Screencast**

The screencast below clearly shows the background, moethod, result and conclusion of our project.
