---
title: "Final Ideas"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The motivation for this project
* Our intended motivation is to create a website to communicate information on the COVID-19 epidemic. More specifically, we would like to focus on excess deaths.

# Relationships that we can explore
* excess death vs. prevention measures taken
  + whether a state implemented mask mandate
  + whether a state implemented travel restrictions
  + whether a state implemented shutdowns
  + whether a state implemented curfews
* excess death vs. demographic numbers
  + excess death vs ethnicities
  + excess death vs age groups
  + excess death vs population densities
* excess death vs. public attitudes
  + trump share vs biden share
  + vote by mail vs in person voting
  + polling differences 

# Potential results
* what are the best public health measures that can be taken that balances prevention of COVID-19 with the risk of triggering other public health crisis (domestic violence/drug overdose)
  + what kind of measures should be used for each groups
* How does public opinion/partisan identity contribute/prevent successful measures of containing the COVID-19.
* beware of the time effect on the excess death rate (recent death/hospitalization will be lower than the beginning of the pandemic as doctors have more familiarity with treatment of the disease)

# The anticipated data sources
* We will be initially using a data source from the CDC. This data source displays information excess deaths associated with COVID-19.
https://www.cdc.gov/nchs/nvss/vsrr/covid19/excess_deaths.htm
* https://www.nytimes.com/interactive/2020/11/03/us/elections/results-president.html 2020 election data (maybe we can scrap)
* https://covidtracking.com/ total COVID cases/hospitalization/deaths tracking by states
* https://www.census.gov/data/datasets.html census data for state's demographic chracteristics

