---
title: "Final Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

<br>

### Motivation

Since the beginning of COVID-19 pandemic, a range of conspiracy theories and pseudo-intellectual arguments have spun up around the globe about the scope and severity of the pandemic. The [President of The United States](https://apnews.com/article/virus-outbreak-donald-trump-ap-fact-check-anthony-fauci-flu-fe474f0c15f76adf324791a2cfc1e2bb) has repeatedly compared coronavirus to the flu, claiming that the lethality of the two diseases are comparable. While public health professionals can quickly dismiss these statements as nonsensical absurdities, they are actually not unusual opinions amongst the general public. As the daily COVID Death toll reaching new heights in the United States, 30% of Americans are still [not concerned](https://projects.fivethirtyeight.com/coronavirus-polls/) with the virus according to the newest tracking poll from Fivethirtyeight. One major talking point of many COVID skeptics is that they believe the COVID-19's death toll is inflated by hospital reporting other diseases under the name of COVID-19 - therefore, COVID-19 has not increased total mortality rate dramatically.

In addition, as the pandemic had  worn on, the general public has grown increasingly skeptical of the preventive measures that public health officials are promoting throughout the developed world, the idea that ["lockdowns kill people"](https://www.radiologybusiness.com/topics/policy/scott-atlas-radiologist-white-house-covid-19-fauci) has been picked up by an increasingly large portions of pundits, activists and elected officials alike. Opponents of lockdowns claim that these restrictions have significant negative impacts on other aspects of public health, and those consequences vastly outweigh the the supposed benefits that these preventive measures are intended for. One of the most notable proponents of a "return to normal" approach is an organization named the [Great Barrington Declaration](https://gbdeclaration.org/), a group of epidemiologists and doctors who believe that reaching herd immunity instead of curbing the immediate spread of the virus is the "more compassionate approach that balances the risks and benefits".

<br>

### Related Work

* [A closer look at U.S. deaths due to COVID-19](https://www.jhunewsletter.com/article/2020/11/a-closer-look-at-u-s-deaths-due-to-covid-19)
  + A study from one Johns Hopkins researcher that claims that COVID-19 has not significantly impact neither the composition or the quantity of deaths reported in the United States from 2020. The letter had been widely circulated amongst right-wing websites and the university retracted the letter recently.
* [Herd Immunity for COVID-19](https://www.thelancet.com/journals/lanres/article/PIIS2213-2600(20)30555-5/fulltext)
  + A study that examines the arguments for anti-lockdown epidemiologists and their counter parts.
* [Risk Perception Through the Lens of Politics in the Time of the COVID-19 Pandemic](https://www.nber.org/papers/w27008)
  + A study that examines how pre-existing political affiliations and beliefs shape people's perception of the COVID-19 pandemic. It also examines to what extent polarization cripples government-led pandemic responses.
* [COVID-19: a need for real-time monitoring of weekly excess deaths](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)30933-8/fulltext)
  + Journal article details the reasons as well as stressing the importance of excess death data in interpreting the impact of COVID-19.

<br>

### Exploratory Analyses/Initial Questions

The project seeks to answer the following questions that would convince the COVID-19 "skeptics" and "truthers" on the severity of the pandemic as well as the effectiveness/necessity of public preventive measures.  

* What do the excess deaths data of 2020 look like? Is excess deaths data of 2020 significantly different from recent years?  
* Is COVID-19 responsible for the increase (or lack thereof) in excess deaths. If not, what are the other causes?  
* Are the pandemic prevention measures such as travel restrictions and lockdowns contributing associated with significant negative public health consequences?  
* How effective are those pandemic prevention measures in reducing the casualties caused by COVID-19?  

<br>


### Aditional Analyses

This project was intended to provide a data-driven, intuitive explainer for COVID-19 "skeptics" and "truthers". We believe that communicating to the general public about the dire situation that COVID-19 has brought is imperative for any public policy and prevention methods to work as they intended to - curbing the spread of a contagious virus needs a whole of society approach that requires cooperation from all citizens. We originally expected to create predictive matrix and interactive models that would visualize the effectiveness of COVID-19 prevention outcomes. However, we believe that such attempts would not yield the most useful/honest results for that we cannot account for many confounding factors as well as the issue of reverse causation. For example, we have seen that the spread of COVID-19 has positive correlation with the amount of time that people spend indoors. This factor is difficult control for as both cold and warm weather might lead to people 


<br>

### Data

***Excess Deaths Associated with COVID-19*** is from the [Centers for Disease Control and Prevention](https://data.cdc.gov/NCHS/Excess-Deaths-Associated-with-COVID-19/xkkf-xrst/). Excess deaths data is free public data published by Centers for Disease Control and Prevention. Estimates of excess deaths presented in this webpage were calculated using Farrington surveillance algorithms (1). For each jurisdiction, a model is used to generate a set of expected counts, and the upper bound of the 95% Confidence Intervals (95% CI) of these expected counts is used as a threshold to estimate excess deaths. Observed counts are compared to these upper bound estimates to determine whether a significant increase in deaths has occurred. The site provided csv files for download.

***Provisional COVID-19 Death Counts by Week Ending Date and State*** was obtained from the [Centers for Disease Control and Prevention](https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-by-Week-Ending-D/r8kw-7aab). Deaths involving coronavirus disease 2019 (COVID-19), pneumonia, and influenza reported to NCHS by week ending date and by state. The site provided csv files for download.

***COVID-19 Prevention Methods by States*** was obtained from the [National Academy of State Health Policy](https://www.nashp.org/governors-prioritize-health-for-all/). We import and link data on the lengths of each states stay-at-home-orders, mask mandate as well as travel restrictions based on information aggregated from by the National Academy of State Health Policy. The data was scrapped using `rvest`.

***State Population Totals: 2010 - 2019*** was obtained from the [United States Census Bureau](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-state-total.html). We import and link data on the population and demographic information for each state to further our analysis on COVID impacts as well as prevention outcomes. The site provided csv files for download.

<br>

### Discussion

**COVID-19 Impacts**

To accurately examine the impact of the coronavirus pandemic, our analysis follows a step-by-step progression that began with analyzing the total reported deaths from 2017 to 2020 up till October, the last month where we have complete statistics for. The total reported deaths of 2020 stands at 2,730,419, which is 15% higher than the closest year 2019's reported deaths of 2,342,978. In terms of monthly reported deaths, the year 2020 has seen multiple months with reported deaths over 300,000 - a number that no previous records have reached. In conclusion, we can say that there is a significant increase in total deaths occurring in the year of 2020.

Secondly, we investigate the nature of the increased reported deaths - whether the deaths are naturally is a product environmental factor and population growth or some shock event that drastically drives up the mortality rate. By calculating the excess death counts (or lackthereof) from 2017 - 2020, we see that until March 2020, the observed death numbers have been consistently below the expected deaths upperbound threshold (95% CI) with afew exceptions. The past 8 months have seen a radical departure from norm for the excess deaths number, suggesting that there was one unexpected event that triggered the rise in mortality reporting.

In order to confirm that the 'shock event' that triggered mass casualties reported was indeed COVID-19, we conducted simple linear regression to examine the association between COVID-19 deaths reported and total excess deaths. The regression yielded a high $R^2$ value at 0.94, indicating that almost all variations in excess deaths can be explained by increase in COVID-19 deaths. The scatterplot graph also demonstrated that there exists an almost 1 to 1 relationship between the two variables. Hence we conclude that COVID-19 is indeed the culprit for the mass sike in casulties in 2020.

To further explore the true toll of the coronavirus pandemic, we dive in to see if the COVID-19 deaths report underestimate or overestimate the true impact of the pandemic. We did so by investigate the relationship between non-COVID 19 excess deaths and reported COVID-19 deaths. It turns out that COVID-19 and non-COVID-19 excess deaths are highly correlated, indicating that there is underreporting of deaths caused by COVID-19 and the real pandemic death count is likely to be significantly higher than the reported number.

After establishing that COVID-19 is indeed a mass casulties event that cannot be simply dismissed as "the flu", we looked at the specific data for each individual state to ascertain which states have taken the heaviest hit so far in the pandemic. We found that New Jersey, New York, Louisiana and Missisipi are all states that have seen a significant increase in excess deaths compared to historical records and on per capita basis. The pacific states (CA,WA,OR,AL,HI) and New England (MA,ME,VT,NH) are the two regions that have done the best job in terms of  COVID-19 prevention.

**Prevention Outcomes**

